---
- name: configure new ruVDS servers
  hosts: ruvds

  tasks:
      
    - name: копируем файл сайта   
      ansible.builtin.command: curl https://raw.githubusercontent.com/swargg/swargg.ru/refs/heads/main/index.html -o /root/www/index.html

    - name: перезапускаем контейнер
      ansible.builtin.command: docker restart swarggru